/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pruebaFinal.vista;

import com.pruebaFinal.controlador.ModeloAgendaContactos;
import com.pruebaFinal.modelo.Contacto;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JONA
 */
public class AgendaJFrame extends javax.swing.JFrame
{

    public JTextField getjTextFieldBusqueda()
    {
        return jTextFieldBusqueda;
    }

    public void setjTextFieldBusqueda(JTextField jTextFieldBusqueda)
    {
        this.jTextFieldBusqueda = jTextFieldBusqueda;
    }


    
    /**
     * Creates new form AgendaJFrame
     */
    public AgendaJFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jRadioButtonBuscarNombre = new javax.swing.JRadioButton();
        jRadioButtonBuscarOcupación = new javax.swing.JRadioButton();
        jRadioButtonBuscarCumpleaños = new javax.swing.JRadioButton();
        jRadioButtonListarTodos = new javax.swing.JRadioButton();
        jRadioButtonListarFavoritos = new javax.swing.JRadioButton();
        jLabelBusqueda = new javax.swing.JLabel();
        jTextFieldBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("AGENDA DE CONTACTOS");

        jRadioButtonBuscarNombre.setText("Buscar por nombre");
        jRadioButtonBuscarNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonBuscarNombreActionPerformed(evt);
            }
        });

        jRadioButtonBuscarOcupación.setText("Buscar por Ocupación");
        jRadioButtonBuscarOcupación.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonBuscarOcupaciónActionPerformed(evt);
            }
        });

        jRadioButtonBuscarCumpleaños.setText("Buscar por fecha de Cumpleaños");
        jRadioButtonBuscarCumpleaños.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonBuscarCumpleañosActionPerformed(evt);
            }
        });

        jRadioButtonListarTodos.setText("Listar Directorio");
        jRadioButtonListarTodos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonListarTodosActionPerformed(evt);
            }
        });

        jRadioButtonListarFavoritos.setText("Listar Favoritos");
        jRadioButtonListarFavoritos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonListarFavoritosActionPerformed(evt);
            }
        });

        jLabelBusqueda.setText("Busqueda: ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Nombre", "Parentezo", "Ocupación", "Cumpleaños", "E-mail", "Celular", "Teléfono", "Dirección"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Criterios:");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonBuscarOcupación)
                    .addComponent(jRadioButtonBuscarCumpleaños)
                    .addComponent(jRadioButtonListarTodos)
                    .addComponent(jRadioButtonListarFavoritos)
                    .addComponent(jRadioButtonBuscarNombre)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBusqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(425, 425, 425))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonBuscarNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonBuscarOcupación)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonBuscarCumpleaños)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonListarTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonListarFavoritos)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBusqueda)
                            .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonBuscarNombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonBuscarNombreActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonBuscarNombreActionPerformed
        jRadioButtonBuscarOcupación.setSelected(false);
        jRadioButtonBuscarCumpleaños.setSelected(false);
        jRadioButtonListarTodos.setSelected(false);
        jRadioButtonListarFavoritos.setSelected(false);
    }//GEN-LAST:event_jRadioButtonBuscarNombreActionPerformed

    private void jRadioButtonBuscarOcupaciónActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonBuscarOcupaciónActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonBuscarOcupaciónActionPerformed
        jRadioButtonBuscarNombre.setSelected(false);
        jRadioButtonBuscarCumpleaños.setSelected(false);
        jRadioButtonListarTodos.setSelected(false);
        jRadioButtonListarFavoritos.setSelected(false);
    }//GEN-LAST:event_jRadioButtonBuscarOcupaciónActionPerformed

    private void jRadioButtonBuscarCumpleañosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonBuscarCumpleañosActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonBuscarCumpleañosActionPerformed
        jRadioButtonBuscarNombre.setSelected(false);
        jRadioButtonBuscarOcupación.setSelected(false);
        jRadioButtonListarTodos.setSelected(false);
        jRadioButtonListarFavoritos.setSelected(false);
    }//GEN-LAST:event_jRadioButtonBuscarCumpleañosActionPerformed

    private void jRadioButtonListarTodosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonListarTodosActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonListarTodosActionPerformed
        jRadioButtonBuscarNombre.setSelected(false);
        jRadioButtonBuscarOcupación.setSelected(false);
        jRadioButtonBuscarCumpleaños.setSelected(false);
        jRadioButtonListarFavoritos.setSelected(false);
    }//GEN-LAST:event_jRadioButtonListarTodosActionPerformed

    private void jRadioButtonListarFavoritosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonListarFavoritosActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonListarFavoritosActionPerformed
        jRadioButtonBuscarNombre.setSelected(false);
        jRadioButtonBuscarOcupación.setSelected(false);
        jRadioButtonBuscarCumpleaños.setSelected(false);
        jRadioButtonListarTodos.setSelected(false);
    }//GEN-LAST:event_jRadioButtonListarFavoritosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed

        
        if( jRadioButtonBuscarNombre.isSelected())
        {
            busqueda(1,jTextFieldBusqueda.getText());
          
            System.out.println("buscar por nombre");
        }
        else if(jRadioButtonBuscarOcupación.isSelected())
        {
            busqueda(2,jTextFieldBusqueda.getText());
            System.out.println("buscar por ocupacion");
        }
        else if(jRadioButtonBuscarCumpleaños.isSelected())
        {
            busqueda(3,jTextFieldBusqueda.getText());
            System.out.println("cumpleaños");
        }
        else if(jRadioButtonListarTodos.isSelected())
        {
            busqueda(4,jTextFieldBusqueda.getText());
            System.out.println("TODOS");
        }
        else if(jRadioButtonListarFavoritos.isSelected())
        {
            busqueda(5,null);
            System.out.println("fav");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AgendaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AgendaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AgendaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AgendaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AgendaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBusqueda;
    private javax.swing.JRadioButton jRadioButtonBuscarCumpleaños;
    private javax.swing.JRadioButton jRadioButtonBuscarNombre;
    private javax.swing.JRadioButton jRadioButtonBuscarOcupación;
    private javax.swing.JRadioButton jRadioButtonListarFavoritos;
    private javax.swing.JRadioButton jRadioButtonListarTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextField jTextFieldBusqueda;
    // End of variables declaration//GEN-END:variables

    private void busqueda(int i, String text)
    {
                List<Contacto> contactos = new ArrayList<>();
        ModeloAgendaContactos modelo = new ModeloAgendaContactos();
                    contactos = modelo.llenarTabla(i,jTextFieldBusqueda.getText());
            
            DefaultTableModel modeloTabla = (DefaultTableModel)jTable1.getModel();           
            while(modeloTabla.getRowCount() > 0)
            {
                modeloTabla.removeRow(0);
            }
            for (Contacto ct : contactos)
            {
                Date date = ct.getCumpleaños().getTime();             
                SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
                String date1 = format1.format(date);            
                Date inActiveDate = null;
                
                modeloTabla.addRow(new Object[]{ct.getNombre(),ct.getParentezo(),ct.getOcupación(),date1,ct.getAgenda().getEmail(),ct.getAgenda().getCelular(),ct.getAgenda().getTelefono(),ct.getAgenda().getDirección()});
            }
    }
}
